//Application Types
export const GET_ALL_APPLICATION = "GET_ALL_APPLICATION";
export const GET_ALL_APPLICATION_PENDING = "GET_ALL_APPLICATION_PENDING";
export const GET_ALL_APPLICATION_ERROR = "GET_ALL_APPLICATION_ERROR";

//Statistic Types
export const GET_STATISTICS = "GET_STATISTICS";
export const GET_STATISTICS_PENDING = "GET_STATISTICS_PENDING";
export const GET_STATISTICS_ERROR = "GET_STATISTICS_ERROR";
